#!bin/bash

if [ "$(id -u)" -ne "0" ]
  then
	echo "Please login as Root User "
   exit
fi

#collecting hostname

lhost=$(hostname)
rhost_appb=$(echo "$lhost" | sed 's/APPA/APPB/')
rhost_weba=$(echo "$lhost" | sed 's/APPA/WEBA/')
rhost_webb=$(echo "$lhost" | sed 's/APPA/WEBB/')
rhost_bkpa=$(echo "$lhost" | sed 's/APPA/BKPA/')

#Setting VM BASE SRV IP
baseip="$(echo "$(hostname -i | cut -d "." -f1-3)")"
#appabase="$(echo $baseip.141)"
#appbbase="$(echo $baseip.143)"
webabase="$(echo $baseip.131)"
webbbase="$(echo $baseip.133)"
appabase=10.240.13.214
appbbase=10.240.13.215

if [ -e /root/.ssh/id_rsa.pub ]
then
echo " SSH_KeyGen found "
else
echo "SSH_Keygen not found , So creating new Key_gen"
ssh-keygen
fi



for i in $lhost $rhost_weba $rhost_webb $rhost_appb  
  do 
       echo " "
       if [ "$i" == "$lhost" ]
       then
               echo " Checking in AppA_Server "
               echo " "
	       echo "The Feapadmin User ID of "$i" "
 	       echo $(id feapadmin | cut -d '(' -f1 | cut -d '=' -f2)
	       echo "The Feapadmin Group ID of "$i" " 
	       echo $(id feapadmin | cut -d '(' -f2 | cut -d "=" -f2)

sleep 2
		echo " Cheking necessery Services status "
	        echo " "
        	chkconfig --list | grep nfslock
	        chkconfig --list | grep portmap
	        chkconfig --list | grep ntpd
	        chkconfig --list | grep rpcidmapd
	         echo " "  
	        echo " Checking ODBC.ini File in AppA Server "
	        echo " " 
	        echo " The User in the ODBC.ini file under [efeap] is "
	        echo $(cat /etc/odbc.ini | grep  -FA9 '[efeap]' | egrep User |cut -d "=" -f2 | sed 's/ //')
	        echo " The Password in the ODBC.ini file under [efeap] is "
	        echo $(cat /etc/odbc.ini | grep  -FA9 '[efeap]' | egrep Password |cut -d "=" -f2 | sed 's/ //')
	        echo " The Server IP  in the ODBC.ini file under [efeap] is "
	        echo $(cat /etc/odbc.ini | grep  -FA9 '[efeap]' | egrep Server |cut -d "=" -f2 | sed 's/ //')
sleep 3          
        elif [ "$i" == "$rhost_appb" ]
        then  
              
               ssh -T -o PasswordAuthentication=no "$i" echo "   "
               if [ "$?" -ne '0' ]
               then
               ssh-copy-id -i /root/.ssh/id_rsa.pub "$i" 
               else

                echo " Logging and Checking  $i Server  ..............."



                out="$(ssh -T -o StrictHostKeyChecking=no "$i" <<_EOF_

                echo "The Feapadmin User ID of "$i" "
                id feapadmin | cut -d '(' -f1 | cut -d '=' -f2  
                echo "The Feapadmin Group ID of "$i" " 
                id feapadmin | cut -d '(' -f2 | cut -d "=" -f2
sleep 3
                echo " Cheking necessery Services status "
                echo " "
                chkconfig --list | grep nfslock
                chkconfig --list | grep portmap
                chkconfig --list | grep ntpd
                chkconfig --list | grep rpcidmapd
                echo " "  
                echo " The User in the ODBC.ini file under [efeap] is "
                cat /etc/odbc.ini | grep  -FA9 '[efeap]' | egrep User |cut -d "=" -f2 | sed 's/ //'
                echo " The Password in the ODBC.ini file under [efeap] is "
                cat /etc/odbc.ini | grep  -FA9 '[efeap]' | egrep Password |cut -d "=" -f2 | sed 's/ //'
                echo " The Server IP  in the ODBC.ini file under [efeap] is "
                cat /etc/odbc.ini | grep  -FA9 '[efeap]' | egrep Server |cut -d "=" -f2 | sed 's/ //'
_EOF_
)"

            
                echo "The output for the "$i" server is "
                echo " "
                echo "$out" 
          
                fi
         else                  

                 echo " Logging and Checking  $i Server  ..............."
                 echo "$i "
                 ssh -T -o PasswordAuthentication=no "$i" echo "   "
                 if [ "$?" -ne '0' ]
                 then
                 ssh-copy-id -i /root/.ssh/id_rsa.pub "$i"
                 else

		 out="$(ssh -T -o StrictHostKeyChecking=no "$i" <<_EOF_

			echo "The Feapadmin User ID of "$i" "
			id feapadmin | cut -d '(' -f1 | cut -d '=' -f2	
			echo "The Feapadmin Group ID of "$i" " 
			id feapadmin | cut -d '(' -f2 | cut -d "=" -f2

sleep 2
			echo " Cheking necessery Services status "
		        echo " "
			chkconfig --list | grep nfslock
			chkconfig --list | grep portmap
			chkconfig --list | grep ntpd
			chkconfig --list | grep rpcidmapd
		        echo " "  
_EOF_
)"


			echo "The output for the "$i" server is "
			echo " "
			echo "$out" 

                 fi 
            fi  
done


for i in $appabase $appbbase 

do

                 ssh -T -o PasswordAuthentication=no "$i" echo "   "
                 if [ "$?" -ne '0' ]
                 then
                 echo " Copying SSH_Key"
                 ssh-copy-id -i /root/.ssh/id_rsa.pub "$i"
                 else
  
                 lvmout="$(ssh -T -o StrictHostKeyChecking=no "$i" <<_EOF_
                 echo "Checking /etc/lvm/lvm.conf file in "$i"Server "
   
                 grep -F 'filter = [ "a/.*/" ]' /etc/lvm/lvm.conf | grep -v "#"
                	if [ "$?" -eq '0' ];then
   		       	        echo " Entry of "filter = [ "a/.*/" ]" is present in /etc/lvm/lvm.conf of "$i" "
	       		else	
 		                 echo "Please check  "filter = [ "a/.*/" ]" line is commented # or make an entry  in /etc/lvm/lvm.conf of "$i" "
                	fi 
_EOF_
)"
                 fi	      
                 echo "$lvmout" "$i"

                
 done

#
#


